name: Trigger auto deployment for protaskly

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/protaskly-AutoDeployTrigger-0cbc92d0-b023-402f-8f11-ca57674c2028.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PROTASKLY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PROTASKLY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PROTASKLY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: protaskly.azurecr.io
          registryUsername: ${{ secrets.PROTASKLY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PROTASKLY_REGISTRY_PASSWORD }}
          containerAppName: protaskly
          resourceGroup: NetworkWatcherRG
          imageToBuild: protaskly.azurecr.io/protaskly:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


